Repository Terasology/Behaviors, pull requests merged in 2022-01, with the labels that each got.

#89 feat!: Replace Pathfinding with FlexiblePathfinding (part 2)
  assets/behaviors/common/attackFollowedEntity.behavior
  assets/behaviors/common/doRandomMove.behavior
  assets/behaviors/common/follow.behavior
  assets/behaviors/common/restrictedStray.behavior
  assets/behaviors/creatures/worker.behavior
  assets/behaviors/naiveMoveTo.behavior
  assets/behaviors/pathfinding/dynamicPathfindingFollow.behavior
  assets/behaviors/pathfinding/pointPathfindingFollow.behavior
  assets/behaviors/pathfinding/staticPathfindingFollow.behavior
  assets/behaviors/reliableMoveTo.behavior
  assets/prefabs/behaviorNodes/ensureTargetPresent.prefab
  assets/prefabs/behaviorNodes/findPathTo.prefab
  assets/prefabs/behaviorNodes/finddummypathtonode.prefab
  assets/prefabs/behaviorNodes/findpathtonode.prefab
  assets/prefabs/behaviorNodes/moveAlongPath.prefab
  assets/prefabs/behaviorNodes/moveTo.prefab
  assets/prefabs/behaviorNodes/movealongpathnode.prefab
  assets/prefabs/behaviorNodes/movetonode.prefab
  assets/prefabs/behaviorNodes/validatepathnode.prefab
  assets/prefabs/characters/amphibious.prefab
  assets/prefabs/characters/flying.prefab
  assets/prefabs/characters/swimming.prefab
  assets/prefabs/characters/testcharacter.prefab
  assets/prefabs/items/moveto.prefab
  assets/ui/debug.ui
  module.txt
  src/main/java/org/terasology/module/behaviors/actions/ContinuousMoveAlongPathNode.java
  src/main/java/org/terasology/module/behaviors/actions/EnsureTargetPresentAction.java
  src/main/java/org/terasology/module/behaviors/actions/FindDummyPathTo.java
  src/main/java/org/terasology/module/behaviors/actions/FindPathToNode.java
  src/main/java/org/terasology/module/behaviors/actions/MoveAlongPathNode.java
  src/main/java/org/terasology/module/behaviors/actions/MoveToAction.java
  src/main/java/org/terasology/module/behaviors/actions/NearbyBlockRestricted.java
  src/main/java/org/terasology/module/behaviors/actions/SetTargetLocalPlayerNode.java
  src/main/java/org/terasology/module/behaviors/actions/SetTargetToFollowedEntityAction.java
  src/main/java/org/terasology/module/behaviors/actions/SetTargetToNearbyBlockAwayFromInstigatorAction.java
  src/main/java/org/terasology/module/behaviors/actions/SetTargetToNearbyBlockNode.java
  src/main/java/org/terasology/module/behaviors/actions/SetTargetToTerritory.java
  src/main/java/org/terasology/module/behaviors/actions/SetupContinuousMoveNode.java
  src/main/java/org/terasology/module/behaviors/actions/StopMovingAction.java
  src/main/java/org/terasology/module/behaviors/actions/ValidatePath.java
  src/main/java/org/terasology/module/behaviors/components/MinionMoveComponent.java
  src/main/java/org/terasology/module/behaviors/debug/DebugMoveToComponent.java
  src/main/java/org/terasology/module/behaviors/debug/DebugMoveToSystem.java
  src/main/java/org/terasology/module/behaviors/debug/FlexibleMovementDebugLayout.java
  src/main/java/org/terasology/module/behaviors/debug/FlexibleMovementDebugRenderSystem.java
  src/main/java/org/terasology/module/behaviors/plugin/CompositeMovementPlugin.java
  src/main/java/org/terasology/module/behaviors/plugin/FlyingMovementPlugin.java
  src/main/java/org/terasology/module/behaviors/plugin/LeapingMovementPlugin.java
  src/main/java/org/terasology/module/behaviors/plugin/MovementPlugin.java
  src/main/java/org/terasology/module/behaviors/plugin/SwimmingMovementPlugin.java
  src/main/java/org/terasology/module/behaviors/plugin/WalkingMovementPlugin.java
  src/main/java/org/terasology/module/behaviors/systems/MinionMoveSystem.java
  src/main/java/org/terasology/module/behaviors/systems/PluginSystem.java
  src/test/java/org/terasology/module/behaviors/BehaviorTests.java
  src/test/java/org/terasology/module/behaviors/MovementTests.java
Labels: Topic: AI, Status: Needs Testing, Topic: Stabilization

#90 chore: clean up test prefabs
  assets/prefabs/characters/amphibious.prefab
  assets/prefabs/characters/flying.prefab
  assets/prefabs/characters/swimming.prefab
  assets/prefabs/test/testcharacter.prefab
  src/test/java/org/terasology/module/behaviors/MovementTests.java
Labels: Category: Test/QA, Type: Chore, Type: Refactoring

#93 chore: remove no longer existing CharacterMovement fields from prefabs
  assets/prefabs/test/testcharacter.prefab
Labels: Size: S, Topic: Stabilization, Type: Chore

#91 fix: revert replacement of behavior node prefabs for findPathTo, moveAlongPath and moveTo
  assets/prefabs/behaviorNodes/findDummyPathTo.prefab
  assets/prefabs/behaviorNodes/findPathTo.prefab
  assets/prefabs/behaviorNodes/findpathtonode.prefab
  assets/prefabs/behaviorNodes/moveAlongPath.prefab
  assets/prefabs/behaviorNodes/moveTo.prefab
  assets/prefabs/behaviorNodes/movealongpathnode.prefab
  assets/prefabs/behaviorNodes/movetonode.prefab
Labels: Type: Bug, Size: S
