Repository Terasology/Behaviors, pull requests merged in 2022-04, with the labels that each got.

#102 chore: apply workaround for @In malfunction in actions
  assets/prefabs/behaviorNodes/jump.prefab
  assets/prefabs/behaviorNodes/setTargetLocalPlayer.prefab
  assets/prefabs/behaviorNodes/setTargetToNearbyBlock.prefab
  assets/prefabs/jobRemoveBlock.prefab
  src/main/java/org/terasology/module/behaviors/actions/CheckAttackStopAction.java
  src/main/java/org/terasology/module/behaviors/actions/CheckNightAction.java
  src/main/java/org/terasology/module/behaviors/actions/FindPathToNode.java
  src/main/java/org/terasology/module/behaviors/actions/FollowPlayerWithinRangeAction.java
  src/main/java/org/terasology/module/behaviors/actions/MoveToAction.java
  src/main/java/org/terasology/module/behaviors/actions/NearbyBlockRestricted.java
  src/main/java/org/terasology/module/behaviors/actions/PlayMusicAction.java
  src/main/java/org/terasology/module/behaviors/actions/PlaySoundAction.java
  src/main/java/org/terasology/module/behaviors/actions/SetTargetToNearbyBlockAwayFromInstigatorAction.java
  src/main/java/org/terasology/module/behaviors/actions/SetTargetToNearbyBlockNode.java
  src/main/java/org/terasology/module/behaviors/actions/SetTargetToNearbyPlayer.java
  src/main/java/org/terasology/module/behaviors/actions/ValidatePath.java
Labels: Topic: Stabilization, Type: Chore

#105 fix: Prevent movement to origin after spawning
  src/main/java/org/terasology/module/behaviors/actions/FindPathToNode.java
  src/main/java/org/terasology/module/behaviors/components/MinionMoveComponent.java
Labels: Type: Bug, Topic: AI, Size: S

#103 chore: clean up some code
  src/main/java/org/terasology/module/behaviors/actions/LookAtAction.java
  src/main/java/org/terasology/module/behaviors/actions/MoveToAction.java
  src/main/java/org/terasology/module/behaviors/actions/ValidatePath.java
  src/main/java/org/terasology/module/behaviors/components/NPCMovementComponent.java
  src/main/java/org/terasology/module/behaviors/debug/DebugRenderSystem.java
  src/main/java/org/terasology/module/behaviors/debug/FlexibleMovementDebugLayout.java
  src/main/java/org/terasology/module/behaviors/plugin/CompositeMovementPlugin.java
Labels: Type: Chore

#104 refactor: rename checkFleeStopAction -> checkFleeContinueAction
  assets/behaviors/creatures/critter.behavior
  src/main/java/org/terasology/module/behaviors/actions/CheckFleeContinueAction.java
Labels: Type: Refactoring
